[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "arches-rascolls"
readme = "README.md"
authors = [
    {name = "Arches Project"}
]
license = {text = "GNU AGPL3"}
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.13",
    "Framework :: Django",
    "Framework :: Django :: 6.1",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Information Technology",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
]
requires-python = ">=3.12"
dependencies = [
    "arches @ git+https://github.com/archesproject/arches.git@cbyrd/12934-migrate-to-openvue",
    "django_csp==3.8",
    "arches_modular_reports @ git+https://github.com/archesproject/arches-modular-reports.git@cbyrd/migrate-to-openvue",
    "arches_search @ git+https://github.com/archesproject/arches-search.git@cbyrd/migrate-to-openvue",
    "arches_resource_sets>=0.1.0a1",
    "arches-controlled-lists @ git+https://github.com/archesproject/arches-controlled-lists.git@cbyrd/migrate-to-openvue",
    "arches-vue-components @ git+https://github.com/archesproject/arches-vue-components.git@cbyrd/migrate-to-openvue",
]
version = "0.0.1"

[dependency-groups]
dev = [
    "livereload",
    "sst",
    "coverage",
    "django-silk==5.5.0",
    "pre-commit==4.6.1",
    "black==26.3.1",
]

[tool.setuptools]
packages = ["arches_rascolls"]
